apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: murali90102/test
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test
spec:
  selector:
    app: test

  type: NodePort
  ports:
  - nodePort: 31001
    port: 8081
    targetPort: 8081
